{
  "PlutoSign": {
    "Version": "2.0"
  },
  "PlutoQueue": {
      "StarCoinsQueue": 2000,
      "FameQueue": 2000
  },
  "Changelog": [ 
    "! Fixed a Bug",
    "+ Added new Option",
    "! Fixed a Bug",
    "! Fixed a Bug",
    "! Fixed a Bug",
    "! Fixed a Bug",
    "! Fixed a Bug",
    "! Fixed a Bug",
    "! Fixed a Bug",
    "! Fixed a Bug",
    "! Fixed a Bug",
    "! Fixed a Bug",
    "! Fixed a Bug",
    "! Fixed a Bug",
    "! Fixed a Bug",
    "! Fixed a Bug",
    "! Fixed a Bug",
    "! Fixed a Bug",
    "! Fixed a Bug",
    "! Fixed a Bug",
    "! Fixed a Bug",
    "! Fixed a Bug",
    "! Fixed a Bug",
    "! Fixed a Bug",
    "! Fixed a Bug",
    "! Fixed a Bug",
    "! Fixed a Bug",
    "! Fixed a Bug",
    "! Fixed a Bug",
    "! Fixed a Bug",
    "! Fixed a Bug",
    "! Fixed a Bug",
    "! Fixed a Bug",
    "! Fixed a Bug",
    "! Fixed a Bug",
    "! Fixed a Bug",
    "! Fixed a Bug",
    "! Fixed a Bug",
    "! Fixed a Bug",
    "! Fixed a Bug",
    "! Fixed a Bug",
    "! Fixed a Bug",
    "! Fixed a Bug",
    "! Fixed a Bug",
    "! Fixed a Bug",
    "! Fixed a Bug",
    "! Fixed a Bug",
    "! Fixed a Bug",
    "! Fixed a Bug",
    "! Fixed a Bug",
    "! Fixed a Bug",
    "! Fixed a Bug",
    "! Fixed a Bug",
    "! Fixed a Bug",
    "! Fixed a Bug",
    "! Fixed a Bug",
    "! Fixed a Bug",
    "! Fixed a Bug",
    "! Fixed a Bug",
    "! Fixed a Bug",
    "! Fixed a Bug"
  ]
}
